<?php

namespace Azeroth\WorldBundle\Repository;

/**
 * CreatureLootTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatureLootTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
