<?php

namespace Azeroth\WorldBundle\Repository;

/**
 * CreatureTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatureTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
